services:
  - type: web
    name: ogs-exam-portal-backend
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://ogs_admin:OgsPortal2025!@ogs-exam-cluster.orqouyi.mongodb.net/?appName=ogs-exam-cluster
      - key: PORT
        value: 10000
