services:
  - type: web
    name: ogs-exam-portal-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 10000

  - type: static
    name: ogs-exam-portal-client
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
